### ISSUE TITLE
Solicitar lista de compras relacionadas ao cardápio

### ISSUE THREAD

**Issue by BiancaPuertaRocha** [Well-Being-App/well-being#21]
**Descrição**
Como usuário desejo solicitar a lista de compras relacionada ao cardápio selecionado.

**Depende de**
#20 

**Critérios de aceitação**

- Deve permitir que o usuário selecione cardápio para a geração da lista;
- Deve conter todos os alimentos presentes no cardápio gerado por período.

**Tasks**

- [x] Desenvolver tela no Figma que permite a seleção do cardápio já previamente gerado;
- [x] Desenvolver tela que permite a visualização dos dados gerados relativos à lista de compras do cardápio.

**Comment by Arthurcrivilin** [comment]
Já fiz um esboço do que pode ser essa função, fiz o mais básico possível para simplificar as mudanças
