### ISSUE TITLE
Fluxo de cadastro

### ISSUE THREAD

**Issue by Hilst** [Well-Being-App/well-being#4]
Eu como usuário desejo me cadastrar no Well Being App ...

**Comment by Arthurcrivilin** [comment]
Cadastro simples de usuário, poderia ser feito por OAuth e as features desbloqueadas seriam simplesmente, notificações personalizadas e lista de preferidos

**Comment by Hilst** [comment]
Tinha uma parte de anamnese que tínhamos discutido. Vamos fazer um forms ou algo parecido
@BiancaPuertaRocha se puder dar uma ideia do que estava pensando

**Comment by BiancaPuertaRocha** [comment]
A parte de anamnese deve estar inclusa no app como um formulário que é apresentado assim que a pessoa se cadastra no sistema, no primeiro acesso. Assim ela insere os dados dela (como peso, altura, idade, se fumante, alergias, dentre outros dados que serao necessários para que o sistema processe as sugestões).
Mas acho que essa parte podia ser por ex no primeiro acesso e não diretamente junto com os registros de cadastro do usuário.

**Comment by Hilst** [comment]
Poderíamos separar a anamnésia em uma outra tela/fluxo e outro CU. Uma issue de cadastro OAuth já é bem complexo e já entrega um valor grande para o usuário. Poderia ser um CU relacionado com a tela da Home/Usuário que mencionei  nesse [comentário](https://github.com/Well-Being-App/well-being/issues/7#issuecomment-1206625866)

**Comment by BiancaPuertaRocha** [comment]
O Cadastro do usuario é um caso de uso que tem ligação de **include** com o caso de uso da realização da anamnese. Ou seja, sao casos de uso diferentes mas ao realizar o cadastro, a anamnese precisa ser feita.

**Comment by BiancaPuertaRocha** [comment]
Eu acho que deveria ser obrigatório no momento do cadastro pois nada mais pode ser feito caso isso nao seja realizado, por isso a diferença do comentario anterior sobre a tela. Não precisa estar em outro fluxo necessariamente. Mas caso a intenção seja mesmo que ele possa executar outras funcionalidades sem realizar a anamnese, pode ser separado mesmo (mas eu nao lembro de ter algo que nao necessite dessas infos).

**Comment by Hilst** [comment]
Entendi. Acho que podemos ver como CUs diferentes em um mesmo épico ou feature. Eles não são dependências fortes então podemos pensar como fluxos diferentes encadeados que ficaria mais fácil trabalhar com eles

**Comment by Arthurcrivilin** [comment]
- Usando o FusionAuth, dá pra ter todo o fluxo de CU já "automatizado", na verdade podemos até integrar com nossa API na tela de cadastro colocando mais campos pra ele gerenciar.
- Para o FusionAuth, só precisa de um email ou username (Exclusivo) e a senha, qualquer outra informação é opcional e podemos personalizar ao pedir mais...

- Tenho aqui uma calculadora que faz o gasto energético com base em alguns dados, acho que é o suficiente para nossa aplicação: https://www.tuasaude.com/saiba-quantas-calorias-gasta-por-dia/
- Só precisamos escolher o que precisamos e pontuarmos.
