### ISSUE TITLE
Estruturar Arquitetura Front

### ISSUE THREAD

**Issue by Hilst** [Well-Being-App/well-being#5]
# Objetivo
Definir tecnologias relacionadas ao Frontend

# DOD
- Definição textual no arquivo arquitetura.md na partição de frontend
- Motivação textual da tecnologia

# Tasks
- [ ] ...

**Comment by Arthurcrivilin** [comment]
Sugestão de uso sendo React ou HTML legado com bootstrap

**Comment by Hilst** [comment]
A escolha acho que seria só entre Nativo ou JS. Não sei se react tem integração com agenda e tals, mas pode ser JS sim
