### ISSUE TITLE
Tela Alimentações

### ISSUE THREAD

**Issue by Hilst** [Well-Being-App/well-being#7]

**Comment by Arthurcrivilin** [comment]
Tela inicial com interface parecia com Instagram, botões no footer e imagens como cards para mostrar as alimentações sugeridas ao usuário

Footer conter: 
Home, Preferidos, Usuário

Cards:
Imagem no fundo, cantos arredondados e footer com Título

**Comment by Hilst** [comment]
Acho no caso o footer poderia direcionar para outras features do app, deixaria o usuário como Home, removeria os preferidos, mas adicionaria a agenda:

Ficaria algo tipo isso para o Footer:
Alimentação , Usuário, Agenda
Só para navegação mesmo

No Header pomos as funções específicas das funções. Aí teria um "adicione mais" e "preferências"
