### ISSUE TITLE
Tela Agenda

### ISSUE THREAD

**Issue by Hilst** [Well-Being-App/well-being#8]

**Comment by Arthurcrivilin** [comment]
Não sei se a gente precisa fazer essa tela... Acho interessante fazer uma integração com o google agenda, ficar fazendo app com agenda é muito mais difícil.

**Comment by Hilst** [comment]
Pode ser só uma tela para criar agenda que relaciona com a agenda real do device

**Comment by BiancaPuertaRocha** [comment]
acho que seria mais a tela de configuração de que notificações vc quer que apareça, como lembrete pra tomar agua, remédios, alimentação (tem gente que tem que se alimentar de 3 em 3 horas e tal)
